### ISSUE TITLE
Broken Link to acquire `data/values.json`, cannot update `user-select`

### ISSUE THREAD

**Issue by thechriswalker** [ben-eb/postcss-reduce-initial#17]
The URL https://developer.mozilla.org/en-US/docs/Template:CSSData is now a broken link, searching there does not seem to be a "single-page" version, only each property explicitly.

I came across this because the plugin was changing `user-select: initial` to `user-select:none` when `initial` was used to reset a previous `none` declaration. According to https://developer.mozilla.org/en-US/docs/Web/CSS/user-select, the `initial` value should be `auto` not `none`.

**Comment by ben-eb** [comment]
Hi @thechriswalker,

Yeah, actually Mozilla have moved the dataset to https://github.com/mdn/data/blob/master/css, I've just been really busy and haven't been able to update the script yet. You can see that there was a recent pull request to update this value https://github.com/mdn/data/pull/27.

I'd be willing to accept a pull request that points to the new dataset. I think it might be enough to point at the raw `properties.json` file on GitHub https://raw.githubusercontent.com/mdn/data/master/css/properties.json and pull that in instead, parsing it as JSON. We can drop the cheerio dependency at the same time.

Would you be willing to do this for me? Thanks! 😄
